# Generated by Django 2.2 on 2019-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190514_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='votes',
            new_name='downVotes',
        ),
        migrations.AddField(
            model_name='post',
            name='upVotes',
            field=models.IntegerField(default=0),
        ),
    ]
