# Generated by Django 2.2 on 2019-05-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='address',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
